### GET request to example server
GET http://localhost:8080/members

###팀 id 팀 name 조회
GET http://localhost:8080/teams

###팀 추가
POST http://localhost:8080/teams/add
Content-Type: application/json

{
  "name": "토트넘"
}

### 이름으로 조회
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "name"
}

### 팀명 변경
PUT http://localhost:8080/teams/update/5
Content-Type: application/json

{
  "name": "FC수원"
}

### 회원 이름으로 조회
GET localhost:8080/search?name=김축구

### 팀에 멤버 정보 추가
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "김축구",
  "team": {
    "id": 5
  }
}
