name: Java CI with Gradle and S3 Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: spring-cicd-bucket1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. Build (Test 제외)
      - name: Build project without tests
        run: ./gradlew clean build -x test

      # 6. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 7. S3에 JAR 업로드
      - name: Upload JAR to S3
        run: |
          aws s3 cp build/libs/*.jar s3://${{ env.S3_BUCKET_NAME }}/ --region ${{ env.AWS_REGION }}